[package]
name = "monowiki-types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared types for monowiki"

[dependencies]
serde = { workspace = true }
